// ---------------------------------------------------------------------------
// Author:        David Gilinsky
// File:          src/db/database.cpp
// Purpose:       Implementation of the MariaDB (libmariadb) database layer.
//                String inputs are escaped with mysql_real_escape_string;
//                numeric values are generated by this code, not user strings.
// Created:       2026-07-18
// Last Modified: 2026-07-18
// Version:       0.1.0
// License:       GPL-3.0-or-later
// ---------------------------------------------------------------------------
#include "database.hpp"

#include <mysql.h>

#include <cstdlib>
#include <sstream>
#include <stdexcept>

namespace nightwatcher::db {

struct Database::Impl {
    MYSQL* conn = nullptr;
};

DbConfig DbConfig::from_env() {
    DbConfig c;
    if (const char* v = std::getenv("NW_DB_HOST")) c.host = v;
    if (const char* v = std::getenv("NW_DB_PORT")) c.port = static_cast<uint16_t>(std::atoi(v));
    if (const char* v = std::getenv("NW_DB_USER")) c.user = v;
    if (const char* v = std::getenv("NW_DB_PASSWORD")) c.password = v;
    if (const char* v = std::getenv("NW_DB_NAME")) c.database = v;
    return c;
}

Database::Database(const DbConfig& cfg) : impl_(std::make_unique<Impl>()) {
    impl_->conn = mysql_init(nullptr);
    if (impl_->conn == nullptr) {
        throw std::runtime_error("mysql_init failed");
    }
    if (mysql_real_connect(impl_->conn, cfg.host.c_str(), cfg.user.c_str(),
                           cfg.password.c_str(), cfg.database.c_str(), cfg.port, nullptr,
                           0) == nullptr) {
        const std::string err = mysql_error(impl_->conn);
        mysql_close(impl_->conn);
        impl_->conn = nullptr;
        throw std::runtime_error("cannot connect to MariaDB (" + cfg.user + "@" + cfg.host +
                                 ":" + std::to_string(cfg.port) + "/" + cfg.database +
                                 "): " + err);
    }
}

Database::~Database() {
    if (impl_ && impl_->conn) mysql_close(impl_->conn);
}

std::string Database::esc(const std::string& s) {
    std::string out;
    out.resize(s.size() * 2 + 1);
    const unsigned long n =
        mysql_real_escape_string(impl_->conn, out.data(), s.c_str(), s.size());
    out.resize(n);
    return out;
}

void Database::exec(const std::string& sql) {
    if (mysql_query(impl_->conn, sql.c_str()) != 0) {
        throw std::runtime_error(std::string("query failed: ") + mysql_error(impl_->conn));
    }
}

void Database::upsert_sensor(const SensorRow& s) {
    std::ostringstream q;
    q << "INSERT INTO sensors (id, name, transport, address) VALUES ('" << esc(s.id) << "', '"
      << esc(s.name) << "', '" << esc(s.transport) << "', '" << esc(s.address) << "') "
      << "ON DUPLICATE KEY UPDATE name=VALUES(name), transport=VALUES(transport), "
         "address=VALUES(address)";
    exec(q.str());
}

std::vector<SensorRow> Database::sensors() {
    exec("SELECT id, name, transport, address FROM sensors ORDER BY id");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) {
        throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    }
    std::vector<SensorRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) {
        SensorRow s;
        s.id = row[0] ? row[0] : "";
        s.name = row[1] ? row[1] : "";
        s.transport = row[2] ? row[2] : "";
        s.address = row[3] ? row[3] : "";
        out.push_back(s);
    }
    mysql_free_result(res);
    return out;
}

std::optional<SensorRow> Database::find_sensor(const std::string& id) {
    std::ostringstream q;
    q << "SELECT id, name, transport, address FROM sensors WHERE id='" << esc(id) << "' LIMIT 1";
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) {
        throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    }
    std::optional<SensorRow> out;
    if (MYSQL_ROW row = mysql_fetch_row(res)) {
        SensorRow s;
        s.id = row[0] ? row[0] : "";
        s.name = row[1] ? row[1] : "";
        s.transport = row[2] ? row[2] : "";
        s.address = row[3] ? row[3] : "";
        out = s;
    }
    mysql_free_result(res);
    return out;
}

void Database::remove_sensor(const std::string& id) {
    std::ostringstream q;
    q << "DELETE FROM sensors WHERE id='" << esc(id) << "'";
    exec(q.str());
}

long long Database::insert_reading(const std::string& sensor_id, const sqm::Reading& r,
                                   const std::string& ts_utc, const std::string& source,
                                   const std::string& quality) {
    std::ostringstream q;
    q << "INSERT IGNORE INTO readings "
         "(sensor_id, ts_utc, mag_arcsec2, freq_hz, period_counts, period_s, temp_c, "
         "quality, source, raw_line) VALUES ('"
      << esc(sensor_id) << "', "
      << (ts_utc.empty() ? std::string("UTC_TIMESTAMP()") : ("'" + esc(ts_utc) + "'")) << ", "
      << r.mag_arcsec2 << ", " << r.freq_hz << ", " << r.period_counts << ", " << r.period_s
      << ", " << r.temp_c << ", '" << esc(quality) << "', '" << esc(source) << "', '"
      << esc(r.raw) << "')";
    exec(q.str());
    return static_cast<long long>(mysql_insert_id(impl_->conn));
}

std::vector<ReadingRow> Database::readings(const std::string& sensor_id, int limit) {
    if (limit < 1) limit = 1;
    std::ostringstream q;
    q << "SELECT id, sensor_id, ts_utc, mag_arcsec2, freq_hz, period_counts, period_s, "
         "temp_c, quality, source, raw_line FROM readings WHERE sensor_id='"
      << esc(sensor_id) << "' ORDER BY ts_utc DESC, id DESC LIMIT " << limit;
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) {
        throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    }
    std::vector<ReadingRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) {
        ReadingRow rr;
        rr.id = row[0] ? std::atoll(row[0]) : 0;
        rr.sensor_id = row[1] ? row[1] : "";
        rr.ts_utc = row[2] ? row[2] : "";
        rr.mag_arcsec2 = row[3] ? std::atof(row[3]) : 0.0;
        rr.freq_hz = row[4] ? std::atoll(row[4]) : 0;
        rr.period_counts = row[5] ? std::atoll(row[5]) : 0;
        rr.period_s = row[6] ? std::atof(row[6]) : 0.0;
        rr.temp_c = row[7] ? std::atof(row[7]) : 0.0;
        rr.quality = row[8] ? row[8] : "";
        rr.source = row[9] ? row[9] : "";
        rr.raw_line = row[10] ? row[10] : "";
        out.push_back(rr);
    }
    mysql_free_result(res);
    return out;
}

void Database::insert_calibration(const std::string& sensor_id, const sqm::Calibration& c,
                                  const std::string& ts_utc) {
    std::ostringstream q;
    q << "INSERT INTO config_log "
         "(sensor_id, ts_utc, event_type, light_cal_offset, dark_cal_period_s, "
         "temp_light_c, sensor_offset, temp_dark_c, raw) VALUES ('"
      << esc(sensor_id) << "', "
      << (ts_utc.empty() ? std::string("UTC_TIMESTAMP()") : ("'" + esc(ts_utc) + "'"))
      << ", 'calibration', " << c.light_cal_offset << ", " << c.dark_cal_period_s << ", "
      << c.temp_light_c << ", " << c.sensor_offset << ", " << c.temp_dark_c << ", '"
      << esc(c.raw) << "')";
    exec(q.str());
}

}  // namespace nightwatcher::db
