// ---------------------------------------------------------------------------
// Author:        David Gilinsky
// File:          src/db/database.cpp
// Purpose:       Implementation of the MariaDB (libmariadb) database layer.
//                String inputs are escaped with mysql_real_escape_string;
//                numeric values are generated by this code, not user strings.
// Created:       2026-07-18
// Last Modified: 2026-07-18
// Version:       0.1.0
// License:       GPL-3.0-or-later
// ---------------------------------------------------------------------------
#include "database.hpp"

#include <mysql.h>

#include <algorithm>
#include <cstdlib>
#include <istream>
#include <ostream>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace nightwatcher::db {

struct Database::Impl {
    MYSQL* conn = nullptr;
};

DbConfig DbConfig::from_env() {
    DbConfig c;
    if (const char* v = std::getenv("NW_DB_HOST")) c.host = v;
    if (const char* v = std::getenv("NW_DB_PORT")) c.port = static_cast<uint16_t>(std::atoi(v));
    if (const char* v = std::getenv("NW_DB_USER")) c.user = v;
    if (const char* v = std::getenv("NW_DB_PASSWORD")) c.password = v;
    if (const char* v = std::getenv("NW_DB_NAME")) c.database = v;
    return c;
}

Database::Database(const DbConfig& cfg) : impl_(std::make_unique<Impl>()) {
    impl_->conn = mysql_init(nullptr);
    if (impl_->conn == nullptr) {
        throw std::runtime_error("mysql_init failed");
    }
    // Accept a convenience "host:port" form in the host field (single colon only,
    // so IPv6 literals are left alone). An explicit cfg.port still applies if no
    // suffix is present.
    std::string host = cfg.host;
    unsigned int port = cfg.port;
    if (std::count(host.begin(), host.end(), ':') == 1) {
        const auto colon = host.find(':');
        const std::string p = host.substr(colon + 1);
        if (!p.empty() && p.find_first_not_of("0123456789") == std::string::npos) {
            port = static_cast<unsigned int>(std::atoi(p.c_str()));
            host = host.substr(0, colon);
        }
    }
    if (mysql_real_connect(impl_->conn, host.c_str(), cfg.user.c_str(), cfg.password.c_str(),
                           cfg.database.c_str(), port, nullptr, 0) == nullptr) {
        const std::string err = mysql_error(impl_->conn);
        mysql_close(impl_->conn);
        impl_->conn = nullptr;
        throw std::runtime_error("cannot connect to MariaDB (" + cfg.user + "@" + host + ":" +
                                 std::to_string(port) + "/" + cfg.database + "): " + err);
    }
}

Database::~Database() {
    if (impl_ && impl_->conn) mysql_close(impl_->conn);
}

std::string Database::esc(const std::string& s) {
    std::string out;
    out.resize(s.size() * 2 + 1);
    const unsigned long n =
        mysql_real_escape_string(impl_->conn, out.data(), s.c_str(), s.size());
    out.resize(n);
    return out;
}

void Database::exec(const std::string& sql) {
    if (mysql_query(impl_->conn, sql.c_str()) != 0) {
        throw std::runtime_error(std::string("query failed: ") + mysql_error(impl_->conn));
    }
}

namespace {

const char* const kSensorCols =
    "id, name, site, serial_number, model, protocol_ver, feature_ver, latitude, "
    "longitude, elevation_m, timezone, transport, address, poll_interval_s, status, "
    "installed_at, notes, created_at";

SensorRow sensor_from_row(MYSQL_ROW row) {
    SensorRow s;
    s.id = row[0] ? row[0] : "";
    s.name = row[1] ? row[1] : "";
    s.site = row[2] ? row[2] : "";
    s.serial_number = row[3] ? row[3] : "";
    s.model = row[4] ? row[4] : "";
    if (row[5]) s.protocol_ver = std::atoi(row[5]);
    if (row[6]) s.feature_ver = std::atoi(row[6]);
    if (row[7]) s.latitude = std::atof(row[7]);
    if (row[8]) s.longitude = std::atof(row[8]);
    if (row[9]) s.elevation_m = std::atof(row[9]);
    s.timezone = row[10] ? row[10] : "";
    s.transport = row[11] ? row[11] : "";
    s.address = row[12] ? row[12] : "";
    s.poll_interval_s = row[13] ? std::atoi(row[13]) : 300;
    s.status = row[14] ? row[14] : "";
    s.installed_at = row[15] ? row[15] : "";
    s.notes = row[16] ? row[16] : "";
    s.created_at = row[17] ? row[17] : "";
    return s;
}

}  // namespace

void Database::upsert_sensor(const std::string& id, const SensorFields& f) {
    std::vector<std::string> cols{"id"};
    std::vector<std::string> vals{"'" + esc(id) + "'"};
    std::vector<std::string> ups;

    const auto addS = [&](const char* c, const std::optional<std::string>& v) {
        if (v) {
            cols.emplace_back(c);
            vals.push_back("'" + esc(*v) + "'");
            ups.push_back(std::string(c) + "=VALUES(" + c + ")");
        }
    };
    const auto addI = [&](const char* c, const std::optional<int>& v) {
        if (v) {
            cols.emplace_back(c);
            vals.push_back(std::to_string(*v));
            ups.push_back(std::string(c) + "=VALUES(" + c + ")");
        }
    };
    const auto addD = [&](const char* c, const std::optional<double>& v) {
        if (v) {
            cols.emplace_back(c);
            vals.push_back(std::to_string(*v));
            ups.push_back(std::string(c) + "=VALUES(" + c + ")");
        }
    };

    addS("name", f.name); addS("site", f.site); addS("serial_number", f.serial_number);
    addS("model", f.model); addI("protocol_ver", f.protocol_ver); addI("feature_ver", f.feature_ver);
    addD("latitude", f.latitude); addD("longitude", f.longitude); addD("elevation_m", f.elevation_m);
    addS("timezone", f.timezone); addS("transport", f.transport); addS("address", f.address);
    addI("poll_interval_s", f.poll_interval_s); addS("status", f.status);
    addS("installed_at", f.installed_at); addS("notes", f.notes);

    std::ostringstream q;
    q << "INSERT INTO sensors (";
    for (size_t i = 0; i < cols.size(); ++i) { if (i) q << ", "; q << cols[i]; }
    q << ") VALUES (";
    for (size_t i = 0; i < vals.size(); ++i) { if (i) q << ", "; q << vals[i]; }
    q << ")";
    if (!ups.empty()) {
        q << " ON DUPLICATE KEY UPDATE ";
        for (size_t i = 0; i < ups.size(); ++i) { if (i) q << ", "; q << ups[i]; }
    }
    exec(q.str());
}

bool Database::update_sensor(const std::string& id, const SensorFields& f) {
    if (!find_sensor(id)) return false;

    std::vector<std::string> sets;
    const auto setS = [&](const char* c, const std::optional<std::string>& v) {
        if (v) sets.push_back(std::string(c) + "='" + esc(*v) + "'");
    };
    const auto setI = [&](const char* c, const std::optional<int>& v) {
        if (v) sets.push_back(std::string(c) + "=" + std::to_string(*v));
    };
    const auto setD = [&](const char* c, const std::optional<double>& v) {
        if (v) sets.push_back(std::string(c) + "=" + std::to_string(*v));
    };

    setS("name", f.name); setS("site", f.site); setS("serial_number", f.serial_number);
    setS("model", f.model); setI("protocol_ver", f.protocol_ver); setI("feature_ver", f.feature_ver);
    setD("latitude", f.latitude); setD("longitude", f.longitude); setD("elevation_m", f.elevation_m);
    setS("timezone", f.timezone); setS("transport", f.transport); setS("address", f.address);
    setI("poll_interval_s", f.poll_interval_s); setS("status", f.status);
    setS("installed_at", f.installed_at); setS("notes", f.notes);

    if (sets.empty()) return true;  // sensor exists; nothing to change

    std::ostringstream q;
    q << "UPDATE sensors SET ";
    for (size_t i = 0; i < sets.size(); ++i) { if (i) q << ", "; q << sets[i]; }
    q << " WHERE id='" << esc(id) << "'";
    exec(q.str());
    return true;
}

std::vector<SensorRow> Database::sensors() {
    exec(std::string("SELECT ") + kSensorCols + " FROM sensors ORDER BY id");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) {
        throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    }
    std::vector<SensorRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) {
        out.push_back(sensor_from_row(row));
    }
    mysql_free_result(res);
    return out;
}

std::optional<SensorRow> Database::find_sensor(const std::string& id) {
    std::ostringstream q;
    q << "SELECT " << kSensorCols << " FROM sensors WHERE id='" << esc(id) << "' LIMIT 1";
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) {
        throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    }
    std::optional<SensorRow> out;
    if (MYSQL_ROW row = mysql_fetch_row(res)) {
        out = sensor_from_row(row);
    }
    mysql_free_result(res);
    return out;
}

void Database::remove_sensor(const std::string& id) {
    std::ostringstream q;
    q << "DELETE FROM sensors WHERE id='" << esc(id) << "'";
    exec(q.str());
}

std::vector<SensorRow> Database::active_sensors() {
    exec(std::string("SELECT ") + kSensorCols +
         " FROM sensors WHERE status='active' ORDER BY id");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) {
        throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    }
    std::vector<SensorRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) {
        out.push_back(sensor_from_row(row));
    }
    mysql_free_result(res);
    return out;
}

void Database::insert_event(const std::string& source, const std::string& level,
                            const std::string& event, const std::string& detail,
                            const std::string& device_id) {
    std::ostringstream q;
    q << "INSERT INTO events (ts_utc, device_id, source, level, event, detail) VALUES ("
      << "UTC_TIMESTAMP(), "
      << (device_id.empty() ? std::string("NULL") : ("'" + esc(device_id) + "'")) << ", '"
      << esc(source) << "', '" << esc(level) << "', '" << esc(event) << "', "
      << (detail.empty() ? std::string("NULL") : ("'" + esc(detail) + "'")) << ")";
    exec(q.str());
}

std::vector<EventRow> Database::recent_events(int limit) {
    if (limit < 1) limit = 1;
    std::ostringstream q;
    q << "SELECT id, ts_utc, device_id, source, level, event, detail FROM events "
         "ORDER BY id DESC LIMIT "
      << limit;
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) {
        throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    }
    std::vector<EventRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) {
        EventRow e;
        e.id = row[0] ? std::atoll(row[0]) : 0;
        e.ts_utc = row[1] ? row[1] : "";
        e.device_id = row[2] ? row[2] : "";
        e.source = row[3] ? row[3] : "";
        e.level = row[4] ? row[4] : "";
        e.event = row[5] ? row[5] : "";
        e.detail = row[6] ? row[6] : "";
        out.push_back(e);
    }
    mysql_free_result(res);
    return out;
}

long long Database::insert_reading(const std::string& sensor_id, const sqm::Reading& r,
                                   const std::string& ts_utc, const std::string& source,
                                   const std::string& quality) {
    std::ostringstream q;
    q << "INSERT IGNORE INTO readings "
         "(sensor_id, ts_utc, mag_arcsec2, freq_hz, period_counts, period_s, temp_c, "
         "quality, source, raw_line) VALUES ('"
      << esc(sensor_id) << "', "
      << (ts_utc.empty() ? std::string("UTC_TIMESTAMP()") : ("'" + esc(ts_utc) + "'")) << ", "
      << r.mag_arcsec2 << ", " << r.freq_hz << ", " << r.period_counts << ", " << r.period_s
      << ", " << r.temp_c << ", '" << esc(quality) << "', '" << esc(source) << "', '"
      << esc(r.raw) << "')";
    exec(q.str());
    return static_cast<long long>(mysql_insert_id(impl_->conn));
}

std::vector<ReadingRow> Database::readings(const std::string& sensor_id, int limit) {
    return readings_between(sensor_id, "", "", limit);
}

std::vector<ReadingRow> Database::readings_between(const std::string& sensor_id,
                                                   const std::string& from, const std::string& to,
                                                   int limit) {
    if (limit < 1) limit = 1;
    std::ostringstream q;
    q << "SELECT id, sensor_id, ts_utc, mag_arcsec2, freq_hz, period_counts, period_s, "
         "temp_c, quality, source, raw_line FROM readings WHERE sensor_id='"
      << esc(sensor_id) << "'";
    if (!from.empty()) q << " AND ts_utc >= '" << esc(from) << "'";
    if (!to.empty()) q << " AND ts_utc <= '" << esc(to) << "'";
    q << " ORDER BY ts_utc DESC, id DESC LIMIT " << limit;
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) {
        throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    }
    std::vector<ReadingRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) {
        ReadingRow rr;
        rr.id = row[0] ? std::atoll(row[0]) : 0;
        rr.sensor_id = row[1] ? row[1] : "";
        rr.ts_utc = row[2] ? row[2] : "";
        rr.mag_arcsec2 = row[3] ? std::atof(row[3]) : 0.0;
        rr.freq_hz = row[4] ? std::atoll(row[4]) : 0;
        rr.period_counts = row[5] ? std::atoll(row[5]) : 0;
        rr.period_s = row[6] ? std::atof(row[6]) : 0.0;
        rr.temp_c = row[7] ? std::atof(row[7]) : 0.0;
        rr.quality = row[8] ? row[8] : "";
        rr.source = row[9] ? row[9] : "";
        rr.raw_line = row[10] ? row[10] : "";
        out.push_back(rr);
    }
    mysql_free_result(res);
    return out;
}

void Database::insert_calibration(const std::string& sensor_id, const sqm::Calibration& c,
                                  const std::string& ts_utc, const std::string& event_type,
                                  const std::string& changed_by, const std::string& note) {
    const std::string type = (event_type == "config_change") ? "config_change" : "calibration";
    std::ostringstream q;
    q << "INSERT INTO config_log "
         "(sensor_id, ts_utc, event_type, light_cal_offset, dark_cal_period_s, "
         "temp_light_c, sensor_offset, temp_dark_c, raw, changed_by, note) VALUES ('"
      << esc(sensor_id) << "', "
      << (ts_utc.empty() ? std::string("UTC_TIMESTAMP()") : ("'" + esc(ts_utc) + "'"))
      << ", '" << type << "', " << c.light_cal_offset << ", " << c.dark_cal_period_s << ", "
      << c.temp_light_c << ", " << c.sensor_offset << ", " << c.temp_dark_c << ", '"
      << esc(c.raw) << "', "
      << (changed_by.empty() ? std::string("NULL") : ("'" + esc(changed_by) + "'")) << ", "
      << (note.empty() ? std::string("NULL") : ("'" + esc(note) + "'")) << ")";
    exec(q.str());
}

std::vector<ConfigLogRow> Database::config_log(const std::string& sensor_id, int limit) {
    if (limit < 1) limit = 1;
    std::ostringstream q;
    q << "SELECT id, ts_utc, event_type, light_cal_offset, dark_cal_period_s, temp_light_c, "
         "sensor_offset, temp_dark_c, interval_s, threshold, raw, changed_by, note "
         "FROM config_log WHERE sensor_id='"
      << esc(sensor_id) << "' ORDER BY id DESC LIMIT " << limit;
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) {
        throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    }
    const auto od = [](const char* v) {
        return v ? std::optional<double>(std::atof(v)) : std::nullopt;
    };
    const auto oi = [](const char* v) {
        return v ? std::optional<int>(std::atoi(v)) : std::nullopt;
    };
    std::vector<ConfigLogRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) {
        ConfigLogRow r;
        r.id = row[0] ? std::atoll(row[0]) : 0;
        r.ts_utc = row[1] ? row[1] : "";
        r.event_type = row[2] ? row[2] : "";
        r.light_cal_offset = od(row[3]);
        r.dark_cal_period_s = od(row[4]);
        r.temp_light_c = od(row[5]);
        r.sensor_offset = od(row[6]);
        r.temp_dark_c = od(row[7]);
        r.interval_s = oi(row[8]);
        r.threshold = od(row[9]);
        r.raw = row[10] ? row[10] : "";
        r.changed_by = row[11] ? row[11] : "";
        r.note = row[12] ? row[12] : "";
        out.push_back(std::move(r));
    }
    mysql_free_result(res);
    return out;
}

namespace {

const char* const kWeatherCols =
    "id, name, site, model, provider, config, transport, address, latitude, longitude, "
    "elevation_m, timezone, poll_interval_s, status, installed_at, notes, created_at";

WeatherStationRow weather_from_row(MYSQL_ROW row) {
    WeatherStationRow w;
    w.id = row[0] ? row[0] : "";
    w.name = row[1] ? row[1] : "";
    w.site = row[2] ? row[2] : "";
    w.model = row[3] ? row[3] : "";
    w.provider = row[4] ? row[4] : "";
    w.config = row[5] ? row[5] : "";
    w.transport = row[6] ? row[6] : "";
    w.address = row[7] ? row[7] : "";
    if (row[8]) w.latitude = std::atof(row[8]);
    if (row[9]) w.longitude = std::atof(row[9]);
    if (row[10]) w.elevation_m = std::atof(row[10]);
    w.timezone = row[11] ? row[11] : "";
    w.poll_interval_s = row[12] ? std::atoi(row[12]) : 300;
    w.status = row[13] ? row[13] : "";
    w.installed_at = row[14] ? row[14] : "";
    w.notes = row[15] ? row[15] : "";
    w.created_at = row[16] ? row[16] : "";
    return w;
}

}  // namespace

void Database::upsert_weather_station(const std::string& id, const WeatherStationFields& f) {
    std::vector<std::string> cols{"id"};
    std::vector<std::string> vals{"'" + esc(id) + "'"};
    std::vector<std::string> ups;
    const auto addS = [&](const char* c, const std::optional<std::string>& v) {
        if (v) { cols.emplace_back(c); vals.push_back("'" + esc(*v) + "'"); ups.push_back(std::string(c) + "=VALUES(" + c + ")"); }
    };
    const auto addI = [&](const char* c, const std::optional<int>& v) {
        if (v) { cols.emplace_back(c); vals.push_back(std::to_string(*v)); ups.push_back(std::string(c) + "=VALUES(" + c + ")"); }
    };
    const auto addD = [&](const char* c, const std::optional<double>& v) {
        if (v) { cols.emplace_back(c); vals.push_back(std::to_string(*v)); ups.push_back(std::string(c) + "=VALUES(" + c + ")"); }
    };
    addS("name", f.name); addS("site", f.site); addS("model", f.model);
    addS("provider", f.provider); addS("config", f.config);
    addS("transport", f.transport); addS("address", f.address);
    addD("latitude", f.latitude); addD("longitude", f.longitude); addD("elevation_m", f.elevation_m);
    addS("timezone", f.timezone); addI("poll_interval_s", f.poll_interval_s);
    addS("status", f.status); addS("installed_at", f.installed_at); addS("notes", f.notes);

    std::ostringstream q;
    q << "INSERT INTO weather_stations (";
    for (size_t i = 0; i < cols.size(); ++i) { if (i) q << ", "; q << cols[i]; }
    q << ") VALUES (";
    for (size_t i = 0; i < vals.size(); ++i) { if (i) q << ", "; q << vals[i]; }
    q << ")";
    if (!ups.empty()) {
        q << " ON DUPLICATE KEY UPDATE ";
        for (size_t i = 0; i < ups.size(); ++i) { if (i) q << ", "; q << ups[i]; }
    }
    exec(q.str());
}

bool Database::update_weather_station(const std::string& id, const WeatherStationFields& f) {
    if (!find_weather_station(id)) return false;
    std::vector<std::string> sets;
    const auto setS = [&](const char* c, const std::optional<std::string>& v) { if (v) sets.push_back(std::string(c) + "='" + esc(*v) + "'"); };
    const auto setI = [&](const char* c, const std::optional<int>& v) { if (v) sets.push_back(std::string(c) + "=" + std::to_string(*v)); };
    const auto setD = [&](const char* c, const std::optional<double>& v) { if (v) sets.push_back(std::string(c) + "=" + std::to_string(*v)); };
    setS("name", f.name); setS("site", f.site); setS("model", f.model);
    setS("provider", f.provider); setS("config", f.config);
    setS("transport", f.transport); setS("address", f.address);
    setD("latitude", f.latitude); setD("longitude", f.longitude); setD("elevation_m", f.elevation_m);
    setS("timezone", f.timezone); setI("poll_interval_s", f.poll_interval_s);
    setS("status", f.status); setS("installed_at", f.installed_at); setS("notes", f.notes);
    if (sets.empty()) return true;
    std::ostringstream q;
    q << "UPDATE weather_stations SET ";
    for (size_t i = 0; i < sets.size(); ++i) { if (i) q << ", "; q << sets[i]; }
    q << " WHERE id='" << esc(id) << "'";
    exec(q.str());
    return true;
}

std::vector<WeatherStationRow> Database::weather_stations() {
    exec(std::string("SELECT ") + kWeatherCols + " FROM weather_stations ORDER BY id");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::vector<WeatherStationRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) out.push_back(weather_from_row(row));
    mysql_free_result(res);
    return out;
}

std::optional<WeatherStationRow> Database::find_weather_station(const std::string& id) {
    std::ostringstream q;
    q << "SELECT " << kWeatherCols << " FROM weather_stations WHERE id='" << esc(id) << "' LIMIT 1";
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::optional<WeatherStationRow> out;
    if (MYSQL_ROW row = mysql_fetch_row(res)) out = weather_from_row(row);
    mysql_free_result(res);
    return out;
}

void Database::remove_weather_station(const std::string& id) {
    std::ostringstream q;
    q << "DELETE FROM weather_stations WHERE id='" << esc(id) << "'";
    exec(q.str());
}

namespace {

std::string sql_opt(const std::optional<double>& v) { return v ? std::to_string(*v) : "NULL"; }
std::string sql_opt(const std::optional<int>& v) { return v ? std::to_string(*v) : "NULL"; }

const char* const kWxReadingCols =
    "id, station_id, ts_utc, temp_c, humidity_pct, dew_point_c, pressure_hpa, pressure_abs_hpa, "
    "wind_speed_ms, wind_gust_ms, wind_dir_deg, rain_rate_mmh, rain_daily_mm, uv_index, solar_wm2, "
    "cloud_cover_pct, source, raw";

WeatherReadingRow wxreading_from_row(MYSQL_ROW row) {
    WeatherReadingRow r;
    r.id = row[0] ? std::atoll(row[0]) : 0;
    r.station_id = row[1] ? row[1] : "";
    r.ts_utc = row[2] ? row[2] : "";
    if (row[3]) r.temp_c = std::atof(row[3]);
    if (row[4]) r.humidity_pct = std::atof(row[4]);
    if (row[5]) r.dew_point_c = std::atof(row[5]);
    if (row[6]) r.pressure_hpa = std::atof(row[6]);
    if (row[7]) r.pressure_abs_hpa = std::atof(row[7]);
    if (row[8]) r.wind_speed_ms = std::atof(row[8]);
    if (row[9]) r.wind_gust_ms = std::atof(row[9]);
    if (row[10]) r.wind_dir_deg = std::atoi(row[10]);
    if (row[11]) r.rain_rate_mmh = std::atof(row[11]);
    if (row[12]) r.rain_daily_mm = std::atof(row[12]);
    if (row[13]) r.uv_index = std::atof(row[13]);
    if (row[14]) r.solar_wm2 = std::atof(row[14]);
    if (row[15]) r.cloud_cover_pct = std::atof(row[15]);
    r.source = row[16] ? row[16] : "";
    r.raw = row[17] ? row[17] : "";
    return r;
}

}  // namespace

std::vector<WeatherStationRow> Database::active_weather_stations() {
    exec(std::string("SELECT ") + kWeatherCols +
         " FROM weather_stations WHERE status='active' ORDER BY id");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::vector<WeatherStationRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) out.push_back(weather_from_row(row));
    mysql_free_result(res);
    return out;
}

long long Database::insert_weather_reading(const WeatherReadingRow& r) {
    std::ostringstream q;
    q << "INSERT IGNORE INTO weather_readings "
         "(station_id, ts_utc, temp_c, humidity_pct, dew_point_c, pressure_hpa, pressure_abs_hpa, "
         "wind_speed_ms, wind_gust_ms, wind_dir_deg, rain_rate_mmh, rain_daily_mm, uv_index, "
         "solar_wm2, cloud_cover_pct, source, raw) VALUES ('"
      << esc(r.station_id) << "', "
      << (r.ts_utc.empty() ? std::string("UTC_TIMESTAMP()") : ("'" + esc(r.ts_utc) + "'")) << ", "
      << sql_opt(r.temp_c) << ", " << sql_opt(r.humidity_pct) << ", " << sql_opt(r.dew_point_c) << ", "
      << sql_opt(r.pressure_hpa) << ", " << sql_opt(r.pressure_abs_hpa) << ", "
      << sql_opt(r.wind_speed_ms) << ", " << sql_opt(r.wind_gust_ms) << ", " << sql_opt(r.wind_dir_deg)
      << ", " << sql_opt(r.rain_rate_mmh) << ", " << sql_opt(r.rain_daily_mm) << ", "
      << sql_opt(r.uv_index) << ", " << sql_opt(r.solar_wm2) << ", " << sql_opt(r.cloud_cover_pct)
      << ", '" << esc(r.source.empty() ? "poll" : r.source) << "', "
      << (r.raw.empty() ? std::string("NULL") : ("'" + esc(r.raw) + "'")) << ")";
    exec(q.str());
    return static_cast<long long>(mysql_insert_id(impl_->conn));
}

std::vector<WeatherReadingRow> Database::weather_readings_between(const std::string& station_id,
                                                                 const std::string& from,
                                                                 const std::string& to, int limit) {
    if (limit < 1) limit = 1;
    std::ostringstream q;
    q << "SELECT " << kWxReadingCols << " FROM weather_readings WHERE station_id='" << esc(station_id)
      << "'";
    if (!from.empty()) q << " AND ts_utc >= '" << esc(from) << "'";
    if (!to.empty()) q << " AND ts_utc <= '" << esc(to) << "'";
    q << " ORDER BY ts_utc DESC, id DESC LIMIT " << limit;
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::vector<WeatherReadingRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) out.push_back(wxreading_from_row(row));
    mysql_free_result(res);
    return out;
}

std::vector<WeatherReadingRow> Database::weather_readings(const std::string& station_id, int limit) {
    return weather_readings_between(station_id, "", "", limit);
}

// ---- Export targets -------------------------------------------------------
namespace {
const char* const kExportCols =
    "id, sensor_id, name, target, config, schedule, schedule_time, interval_s, "
    "last_export_ts, status, notes, created_at, schedule_day";

ExportTargetRow export_from_row(MYSQL_ROW row) {
    ExportTargetRow t;
    t.id = row[0] ? row[0] : "";
    t.sensor_id = row[1] ? row[1] : "";
    t.name = row[2] ? row[2] : "";
    t.target = row[3] ? row[3] : "";
    t.config = row[4] ? row[4] : "";
    t.schedule = row[5] ? row[5] : "";
    t.schedule_time = row[6] ? row[6] : "";
    if (row[7]) t.interval_s = std::atoi(row[7]);
    t.last_export_ts = row[8] ? row[8] : "";
    t.status = row[9] ? row[9] : "";
    t.notes = row[10] ? row[10] : "";
    t.created_at = row[11] ? row[11] : "";
    if (row[12]) t.schedule_day = std::atoi(row[12]);
    return t;
}

ExportLogRow exportlog_from_row(MYSQL_ROW row) {
    ExportLogRow r;
    r.id = row[0] ? std::atoll(row[0]) : 0;
    r.target_id = row[1] ? row[1] : "";
    r.ts_utc = row[2] ? row[2] : "";
    r.from_ts = row[3] ? row[3] : "";
    r.to_ts = row[4] ? row[4] : "";
    r.row_count = row[5] ? std::atoll(row[5]) : 0;
    r.file_name = row[6] ? row[6] : "";
    r.remote_id = row[7] ? row[7] : "";
    r.status = row[8] ? row[8] : "";
    r.detail = row[9] ? row[9] : "";
    return r;
}
}  // namespace

void Database::upsert_export_target(const std::string& id, const ExportTargetFields& f) {
    std::vector<std::string> cols{"id"};
    std::vector<std::string> vals{"'" + esc(id) + "'"};
    std::vector<std::string> ups;
    const auto addS = [&](const char* c, const std::optional<std::string>& v) {
        if (v) { cols.emplace_back(c); vals.push_back("'" + esc(*v) + "'"); ups.push_back(std::string(c) + "=VALUES(" + c + ")"); }
    };
    const auto addI = [&](const char* c, const std::optional<int>& v) {
        if (v) { cols.emplace_back(c); vals.push_back(std::to_string(*v)); ups.push_back(std::string(c) + "=VALUES(" + c + ")"); }
    };
    addS("sensor_id", f.sensor_id); addS("name", f.name); addS("target", f.target);
    addS("config", f.config); addS("schedule", f.schedule); addS("schedule_time", f.schedule_time);
    addI("interval_s", f.interval_s); addI("schedule_day", f.schedule_day); addS("status", f.status); addS("notes", f.notes);

    std::ostringstream q;
    q << "INSERT INTO export_targets (";
    for (size_t i = 0; i < cols.size(); ++i) { if (i) q << ", "; q << cols[i]; }
    q << ") VALUES (";
    for (size_t i = 0; i < vals.size(); ++i) { if (i) q << ", "; q << vals[i]; }
    q << ")";
    if (!ups.empty()) {
        q << " ON DUPLICATE KEY UPDATE ";
        for (size_t i = 0; i < ups.size(); ++i) { if (i) q << ", "; q << ups[i]; }
    }
    exec(q.str());
}

bool Database::update_export_target(const std::string& id, const ExportTargetFields& f) {
    if (!find_export_target(id)) return false;
    std::vector<std::string> sets;
    const auto setS = [&](const char* c, const std::optional<std::string>& v) { if (v) sets.push_back(std::string(c) + "='" + esc(*v) + "'"); };
    const auto setI = [&](const char* c, const std::optional<int>& v) { if (v) sets.push_back(std::string(c) + "=" + std::to_string(*v)); };
    setS("sensor_id", f.sensor_id); setS("name", f.name); setS("target", f.target);
    setS("config", f.config); setS("schedule", f.schedule); setS("schedule_time", f.schedule_time);
    setI("interval_s", f.interval_s); setI("schedule_day", f.schedule_day); setS("status", f.status); setS("notes", f.notes);
    if (sets.empty()) return true;
    std::ostringstream q;
    q << "UPDATE export_targets SET ";
    for (size_t i = 0; i < sets.size(); ++i) { if (i) q << ", "; q << sets[i]; }
    q << " WHERE id='" << esc(id) << "'";
    exec(q.str());
    return true;
}

std::vector<ExportTargetRow> Database::export_targets() {
    exec(std::string("SELECT ") + kExportCols + " FROM export_targets ORDER BY id");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::vector<ExportTargetRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) out.push_back(export_from_row(row));
    mysql_free_result(res);
    return out;
}

std::vector<ExportTargetRow> Database::active_export_targets() {
    exec(std::string("SELECT ") + kExportCols + " FROM export_targets WHERE status='active' ORDER BY id");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::vector<ExportTargetRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) out.push_back(export_from_row(row));
    mysql_free_result(res);
    return out;
}

std::optional<ExportTargetRow> Database::find_export_target(const std::string& id) {
    std::ostringstream q;
    q << "SELECT " << kExportCols << " FROM export_targets WHERE id='" << esc(id) << "' LIMIT 1";
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::optional<ExportTargetRow> out;
    if (MYSQL_ROW row = mysql_fetch_row(res)) out = export_from_row(row);
    mysql_free_result(res);
    return out;
}

void Database::remove_export_target(const std::string& id) {
    std::ostringstream q;
    q << "DELETE FROM export_targets WHERE id='" << esc(id) << "'";
    exec(q.str());
}

void Database::set_export_watermark(const std::string& id, const std::string& last_export_ts) {
    std::ostringstream q;
    q << "UPDATE export_targets SET last_export_ts='" << esc(last_export_ts) << "' WHERE id='" << esc(id) << "'";
    exec(q.str());
}

long long Database::insert_export_log(const ExportLogRow& r) {
    const auto opt = [this](const std::string& s) { return s.empty() ? std::string("NULL") : ("'" + esc(s) + "'"); };
    std::ostringstream q;
    q << "INSERT INTO export_log (target_id, ts_utc, from_ts, to_ts, row_count, file_name, "
         "remote_id, status, detail) VALUES ('"
      << esc(r.target_id) << "', "
      << (r.ts_utc.empty() ? std::string("UTC_TIMESTAMP()") : ("'" + esc(r.ts_utc) + "'")) << ", "
      << opt(r.from_ts) << ", " << opt(r.to_ts) << ", " << r.row_count << ", "
      << opt(r.file_name) << ", " << opt(r.remote_id) << ", '"
      << esc(r.status.empty() ? "ok" : r.status) << "', " << opt(r.detail) << ")";
    exec(q.str());
    return static_cast<long long>(mysql_insert_id(impl_->conn));
}

std::vector<ExportLogRow> Database::export_log(const std::string& target_id, int limit) {
    if (limit < 1) limit = 1;
    std::ostringstream q;
    q << "SELECT id, target_id, ts_utc, from_ts, to_ts, row_count, file_name, remote_id, status, detail "
         "FROM export_log WHERE target_id='" << esc(target_id) << "' ORDER BY ts_utc DESC, id DESC LIMIT "
      << limit;
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::vector<ExportLogRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) out.push_back(exportlog_from_row(row));
    mysql_free_result(res);
    return out;
}

long long Database::delete_readings_before(const std::string& sensor_id, const std::string& ts_utc) {
    std::ostringstream q;
    q << "DELETE FROM readings WHERE sensor_id='" << esc(sensor_id) << "' AND ts_utc < '"
      << esc(ts_utc) << "'";
    exec(q.str());
    return static_cast<long long>(mysql_affected_rows(impl_->conn));
}

void Database::dump_sql(std::ostream& out) {
    out << "-- NightWatcher database backup\n";
    out << "-- Restore with: nwdb restore <file>\n";
    out << "SET NAMES utf8mb4;\n";
    out << "SET FOREIGN_KEY_CHECKS=0;\n";

    exec("SHOW TABLES");
    MYSQL_RES* tres = mysql_store_result(impl_->conn);
    if (tres == nullptr) throw std::runtime_error(std::string("SHOW TABLES: ") + mysql_error(impl_->conn));
    std::vector<std::string> tables;
    while (MYSQL_ROW tr = mysql_fetch_row(tres))
        if (tr[0]) tables.emplace_back(tr[0]);
    mysql_free_result(tres);

    for (const auto& t : tables) {
        // Schema (collapsed to a single line so each statement is one line).
        exec("SHOW CREATE TABLE `" + t + "`");
        std::string create;
        if (MYSQL_RES* cres = mysql_store_result(impl_->conn)) {
            if (MYSQL_ROW cr = mysql_fetch_row(cres))
                if (cr[1]) create = cr[1];
            mysql_free_result(cres);
        }
        for (char& ch : create)
            if (ch == '\n' || ch == '\r') ch = ' ';
        out << "DROP TABLE IF EXISTS `" << t << "`;\n";
        if (!create.empty()) out << create << ";\n";

        // Data, batched into multi-row INSERTs (one statement per line).
        exec("SELECT * FROM `" + t + "`");
        MYSQL_RES* dres = mysql_store_result(impl_->conn);
        if (dres == nullptr)
            throw std::runtime_error("dump " + t + ": " + mysql_error(impl_->conn));
        const unsigned int cols = mysql_num_fields(dres);
        int in_batch = 0;
        constexpr int kBatch = 100;
        while (MYSQL_ROW row = mysql_fetch_row(dres)) {
            const unsigned long* lens = mysql_fetch_lengths(dres);
            out << (in_batch == 0 ? "INSERT INTO `" + t + "` VALUES " : ",") << "(";
            for (unsigned int c = 0; c < cols; ++c) {
                if (c) out << ",";
                if (row[c] == nullptr) out << "NULL";
                else out << "'" << esc(std::string(row[c], lens[c])) << "'";
            }
            out << ")";
            if (++in_batch == kBatch) { out << ";\n"; in_batch = 0; }
        }
        if (in_batch > 0) out << ";\n";
        mysql_free_result(dres);
    }
    out << "SET FOREIGN_KEY_CHECKS=1;\n";
}

long long Database::restore_sql(std::istream& in) {
    long long n = 0;
    std::string line;
    while (std::getline(in, line)) {
        const auto a = line.find_first_not_of(" \t\r");
        if (a == std::string::npos) continue;              // blank line
        if (line.compare(a, 2, "--") == 0) continue;       // comment
        auto e = line.find_last_not_of(" \t\r");
        if (line[e] == ';') {                              // drop the trailing ';'
            if (e == a) continue;                          // a bare semicolon
            --e;
        }
        exec(line.substr(a, e - a + 1));
        ++n;
    }
    return n;
}

std::optional<std::string> Database::get_setting(const std::string& name) {
    std::ostringstream q;
    q << "SELECT value FROM settings WHERE name='" << esc(name) << "' LIMIT 1";
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("get_setting: ") + mysql_error(impl_->conn));
    std::optional<std::string> out;
    if (MYSQL_ROW row = mysql_fetch_row(res)) out = row[0] ? row[0] : "";
    mysql_free_result(res);
    return out;
}

void Database::set_setting(const std::string& name, const std::string& value) {
    std::ostringstream q;
    q << "INSERT INTO settings (name, value) VALUES ('" << esc(name) << "', '" << esc(value)
      << "') ON DUPLICATE KEY UPDATE value=VALUES(value)";
    exec(q.str());
}

void Database::delete_setting(const std::string& name) {
    exec("DELETE FROM settings WHERE name = '" + esc(name) + "'");
}

std::vector<TableCount> Database::schema_status() {
    std::set<std::string> present;
    exec("SELECT table_name FROM information_schema.tables WHERE table_schema = DATABASE()");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) {
        if (row[0]) present.insert(row[0]);
    }
    mysql_free_result(res);

    static const char* const kKnown[] = {"sensors",          "readings",
                                         "config_log",       "events",
                                         "weather_stations", "weather_readings",
                                         "users",            "sessions",
                                         "export_targets",   "export_log",
                                         "settings"};
    std::vector<TableCount> out;
    for (const char* t : kKnown) {
        TableCount tc;
        tc.table = t;
        tc.present = present.count(t) > 0;
        if (tc.present) {
            exec(std::string("SELECT COUNT(*) FROM `") + t + "`");
            MYSQL_RES* cres = mysql_store_result(impl_->conn);
            if (cres != nullptr) {
                if (MYSQL_ROW r = mysql_fetch_row(cres)) tc.rows = r[0] ? std::atoll(r[0]) : 0;
                mysql_free_result(cres);
            }
        }
        out.push_back(tc);
    }
    return out;
}

void Database::run_schema_script(const std::string& sql) {
    // Strip line comments ('--' to end of line), then execute each ';'-terminated
    // statement. Intended for the trusted schema file only.
    std::istringstream in(sql);
    std::string line;
    std::string cleaned;
    while (std::getline(in, line)) {
        const auto p = line.find("--");
        if (p != std::string::npos) line = line.substr(0, p);
        cleaned += line;
        cleaned += '\n';
    }
    std::string stmt;
    const auto flush = [&]() {
        const auto b = stmt.find_first_not_of(" \t\r\n");
        if (b != std::string::npos) {
            const auto e = stmt.find_last_not_of(" \t\r\n");
            exec(stmt.substr(b, e - b + 1));
        }
        stmt.clear();
    };
    for (const char c : cleaned) {
        if (c == ';') {
            flush();
        } else {
            stmt += c;
        }
    }
    flush();
}

namespace {

UserRow user_from_row(MYSQL_ROW row) {
    UserRow u;
    u.id = row[0] ? std::atoll(row[0]) : 0;
    u.username = row[1] ? row[1] : "";
    u.password_hash = row[2] ? row[2] : "";
    u.role = row[3] ? row[3] : "";
    u.must_change_password = row[4] && std::atoi(row[4]) != 0;
    u.created_at = row[5] ? row[5] : "";
    return u;
}

const char* const kUserCols = "id, username, password_hash, role, must_change_password, created_at";

}  // namespace

long long Database::count_users() {
    exec("SELECT COUNT(*) FROM users");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    long long n = 0;
    if (MYSQL_ROW row = mysql_fetch_row(res)) n = row[0] ? std::atoll(row[0]) : 0;
    mysql_free_result(res);
    return n;
}

void Database::create_user(const std::string& username, const std::string& password_hash,
                           const std::string& role, bool must_change_password) {
    std::ostringstream q;
    q << "INSERT INTO users (username, password_hash, role, must_change_password) VALUES ('"
      << esc(username) << "', '" << esc(password_hash) << "', '" << esc(role) << "', "
      << (must_change_password ? 1 : 0) << ")";
    exec(q.str());
}

std::optional<UserRow> Database::find_user(const std::string& username) {
    std::ostringstream q;
    q << "SELECT " << kUserCols << " FROM users WHERE username='" << esc(username) << "' LIMIT 1";
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::optional<UserRow> out;
    if (MYSQL_ROW row = mysql_fetch_row(res)) out = user_from_row(row);
    mysql_free_result(res);
    return out;
}

std::vector<UserRow> Database::users() {
    exec(std::string("SELECT ") + kUserCols + " FROM users ORDER BY username");
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::vector<UserRow> out;
    MYSQL_ROW row;
    while ((row = mysql_fetch_row(res)) != nullptr) out.push_back(user_from_row(row));
    mysql_free_result(res);
    return out;
}

bool Database::set_user_password(const std::string& username, const std::string& password_hash,
                                 bool must_change_password) {
    if (!find_user(username)) return false;
    std::ostringstream q;
    q << "UPDATE users SET password_hash='" << esc(password_hash) << "', must_change_password="
      << (must_change_password ? 1 : 0) << " WHERE username='" << esc(username) << "'";
    exec(q.str());
    return true;
}

bool Database::delete_user(const std::string& username) {
    std::ostringstream q;
    q << "DELETE FROM users WHERE username='" << esc(username) << "'";
    exec(q.str());
    return mysql_affected_rows(impl_->conn) > 0;
}

void Database::create_session(const std::string& token, long long user_id, int ttl_seconds) {
    std::ostringstream q;
    q << "INSERT INTO sessions (token, user_id, expires_at) VALUES ('" << esc(token) << "', "
      << user_id << ", UTC_TIMESTAMP() + INTERVAL " << ttl_seconds << " SECOND)";
    exec(q.str());
}

std::optional<SessionInfo> Database::validate_session(const std::string& token) {
    std::ostringstream q;
    q << "SELECT u.id, u.username, u.role FROM sessions s JOIN users u ON u.id = s.user_id "
         "WHERE s.token='"
      << esc(token) << "' AND s.expires_at > UTC_TIMESTAMP() LIMIT 1";
    exec(q.str());
    MYSQL_RES* res = mysql_store_result(impl_->conn);
    if (res == nullptr) throw std::runtime_error(std::string("store_result: ") + mysql_error(impl_->conn));
    std::optional<SessionInfo> out;
    if (MYSQL_ROW row = mysql_fetch_row(res)) {
        SessionInfo si;
        si.user_id = row[0] ? std::atoll(row[0]) : 0;
        si.username = row[1] ? row[1] : "";
        si.role = row[2] ? row[2] : "";
        out = si;
    }
    mysql_free_result(res);
    return out;
}

void Database::delete_session(const std::string& token) {
    std::ostringstream q;
    q << "DELETE FROM sessions WHERE token='" << esc(token) << "'";
    exec(q.str());
}

void Database::delete_expired_sessions() {
    exec("DELETE FROM sessions WHERE expires_at <= UTC_TIMESTAMP()");
}

}  // namespace nightwatcher::db
